### ISSUE TITLE
Elasticsearch Master Install

### ISSUE THREAD

**Issue by 56115** [winfys/ambari-elasticsearch-service#1]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/ELASTICSEARCH/package/scripts/master.py", line 190, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 329, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/ELASTICSEARCH/package/scripts/master.py", line 45, in install
    except KeyError: Group(group_name=params.elastic_group)
TypeError: __new__() takes at least 2 non-keyword arguments (1 given)

**Comment by 56115** [comment]
你好  安装的时候报错，我的是centos 6.5    python2.6  我的环境有问题吗？

**Comment by winfys** [comment]
发送自 Windows 10 版邮件应用
环境没问题
发件人: 561152
发送时间: 2017年10月13日 12:19
收件人: winfys/ambari-elasticsearch-service
抄送: Subscribed
主题: [winfys/ambari-elasticsearch-service] Elasticsearch Master Install(#1)

Traceback (most recent call last):
File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/ELASTICSEARCH/package/scripts/master.py", line 190, in 
Master().execute()
File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 329, in execute
method(env)
File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/ELASTICSEARCH/package/scripts/master.py", line 45, in install
except KeyError: Group(group_name=params.elastic_group)
TypeError: new() takes at least 2 non-keyword arguments (1 given)
